figshare/fcl

packages/ui/src/helpers/focusTrap.jsx
packages/ui/src/textEditor/components/linkModal/index.jsx
packages/ui/src/textEditor/components/linkModal/index.test.jsx
packages/ui/src/textEditor/components/toolbar/index.test.jsx
packages/ui/src/textEditor/components/toolbarButton/index.test.jsx

updating prop validation issues in tests

---

packages/ui/package.json

- add access public to publishConfig, to publish public package through lerna.

add access public modifier to publish config

---

README.md
packages/ui/package.json

use `github packages` registry.

change registry to github-packages

---

packages/ui/package-lock.json
packages/ui/package.json

**Release 1.0.0**
- removed `lerna` dependency
- updated artefacts

:rocket: rel-1.0.0

---

packages/ui/button/button/index.css
packages/ui/button/genericButton/base.jsx
packages/ui/button/genericButton/base.test.jsx
packages/ui/input/search/constants.js
packages/ui/overlay/content/overlayContent.css
packages/ui/overlay/content/overlayContent.jsx
packages/ui/overlay/footer/overlayFooter.css
packages/ui/overlay/footer/overlayFooter.jsx
packages/ui/overlay/header/overlayHeader.css
packages/ui/overlay/header/overlayHeader.jsx
packages/ui/overlay/header/overlayHeader.test.jsx
packages/ui/overlay/overlay.css
packages/ui/overlay/overlay.jsx
packages/ui/overlay/overlay.test.jsx
packages/ui/textEditor/components/toolbar/index.jsx
packages/ui/textEditor/components/toolbar/index.test.jsx
packages/ui/textEditor/components/toolbarButton/index.css
packages/ui/textEditor/utils/constants.js
packages/ui/toggletip/components/content/index.jsx
packages/ui/toggletip/components/content/index.test.jsx
packages/ui/toggletip/components/trigger/index.test.jsx

resovles: [FIG-29846](https://digital-science.atlassian.net/browse/FIG-29846)
resolves: [FIG-29488](https://digital-science.atlassian.net/browse/FIG-29488)
[FIG-29846]: https://digital-science.atlassian.net/browse/FIG-29846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FIG-29488]: https://digital-science.atlassian.net/browse/FIG-29488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-29796,FIG-29488: integrate changes from core

---

packages/ui/package-lock.json
packages/ui/package.json

release : 1.1.0 package updates.

:rocket: rel-1.1.0

---

packages/ui/button/button/index.css
packages/ui/overlay/header/overlayHeader.css

[FIG-29918](https://digital-science.atlassian.net/browse/FIG-29918)
[FIG-29876](https://digital-science.atlassian.net/browse/FIG-29876)
[FIG-29918]: https://digital-science.atlassian.net/browse/FIG-29918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FIG-29876]: https://digital-science.atlassian.net/browse/FIG-29876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-29918: Private link overlay - scroll bar removed + FIG-29876

---

packages/ui/package-lock.json
packages/ui/package.json

release : 1.1.1
> OverlayHeader close button alignment fixes
> Button height fixes

:rocket: rel-1.1.1

---

packages/ui/fieldError/fieldError.css
packages/ui/fieldError/fieldError.jsx
packages/ui/fieldError/fieldError.test.jsx
stories/alerts/fieldError.stories.mdx

[FIG-30192](https://digital-science.atlassian.net/browse/FIG-30192)
[FIG-30192]: https://digital-science.atlassian.net/browse/FIG-30192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-30192: full-width added

---

packages/ui/input/index.jsx
packages/ui/input/radio/index.css
packages/ui/input/radio/index.jsx
packages/ui/input/radio/index.test.jsx
stories/input/radio/radio.stories.mdx

[FIG-30313](https://digital-science.atlassian.net/browse/FIG-30313)
https://github.com/figshare/fcl/assets/63391401/a54d68ef-1099-4f61-8e19-cb8829dcaab8
[FIG-30313]: https://digital-science.atlassian.net/browse/FIG-30313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-30313: Create Radio component

---

packages/ui/input/radio/index.css
packages/ui/input/radio/index.jsx
packages/ui/input/radio/index.test.jsx
stories/input/radio/radio.stories.mdx

resolves: https://digital-science.atlassian.net/browse/FIG-30434
- scoped styling
- updated outline color
- simplified markup

FIG-30434: updating radio to new UX specs

---

packages/ui/package-lock.json
packages/ui/package.json

- scoped styling
- updated outline color
- simplified markup

:rocket: rel-1.2.1

---

packages/ui/package-lock.json
packages/ui/package.json

- adding `title` support
- adding `toast` support
- adding `isSingleRow` style prop
- adding "barcode" icons (small/medium/large)
- adding "spinner" icon

:rocket: rel-1.2.2

---

packages/ui/package-lock.json
packages/ui/package.json

:rocket: rel-1.2.3

---

packages/ui/package-lock.json
packages/ui/package.json

- added a new `lexical` text editor implementation
- updated `react` dependency to `17`

:rocket: rel-1.3.0

---

packages/ui/textEditor/Lexical/components/Toolbar/Toolbar.css
packages/ui/textEditor/Lexical/editor.css

[FIG-31367](https://digital-science.atlassian.net/browse/FIG-31367)
[FIG-31367]: https://digital-science.atlassian.net/browse/FIG-31367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-31367: fix padding for lexical editor

---

packages/ui/textEditor/Lexical/index.jsx
packages/ui/textEditor/Lexical/nodes/CustomTextNode.jsx

Also fixes:
[FIG-31092](https://digital-science.atlassian.net/browse/FIG-31092)
https://digital-science.atlassian.net/browse/FIG-31102
[FIG-31092]: https://digital-science.atlassian.net/browse/FIG-31092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-31236: fix editor autofocus

---

packages/ui/package-lock.json
packages/ui/package.json

:rocket: rel-1.3.4

---

packages/ui/package-lock.json
packages/ui/package.json

:rocket: rel-1.3.5

---

packages/ui/package-lock.json
packages/ui/package.json

- adding `rtl` support
- additional fixes
- adding `goBack` support

:rocket: rel-1.3.6

---

packages/ui/textEditor/Lexical/index.jsx

[FIG-31389](https://digital-science.atlassian.net/browse/FIG-31389)
[FIG-31389]: https://digital-science.atlassian.net/browse/FIG-31389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-31389: fix validation trigger on toolbar button click

---

packages/ui/button/genericButton/index.jsx
packages/ui/button/genericButton/index.test.jsx

[FIG-31563](https://digital-science.atlassian.net/browse/FIG-31563)
[FIG-31563]: https://digital-science.atlassian.net/browse/FIG-31563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-31563: add delay to tooltip and fix positioning

---

packages/ui/textEditor/Lexical/editor.css

[FIG-31669](https://digital-science.atlassian.net/browse/FIG-31669)
[FIG-31669]: https://digital-science.atlassian.net/browse/FIG-31669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-31669: remove unnecessary overflow scroll

---

packages/ui/input/text/index.jsx
packages/ui/styles/generic/typography.css
packages/ui/textEditor/Lexical/editor.css

[FIG-31761](https://digital-science.atlassian.net/browse/FIG-31761)
[FIG-31686](https://digital-science.atlassian.net/browse/FIG-31686)
[FIG-31761]: https://digital-science.atlassian.net/browse/FIG-31761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FIG-31686]: https://digital-science.atlassian.net/browse/FIG-31686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-31686, FIG-31761, fix inputs not returning to ltr after submit & padding for rtl lists

---

packages/ui/input/text/index.jsx

[FIG-31769](https://digital-science.atlassian.net/browse/FIG-31769)
[FIG-31769]: https://digital-science.atlassian.net/browse/FIG-31769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-31769: add option to lock text direction on text input

---

packages/ui/input/text/index.jsx
packages/ui/popup/content.css
packages/ui/styles/generic/typography.css

[FIG-31761](https://digital-science.atlassian.net/browse/FIG-31761)
[FIG-32029](https://digital-science.atlassian.net/browse/FIG-32029)
[FIG-31761]: https://digital-science.atlassian.net/browse/FIG-31761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FIG-32029]: https://digital-science.atlassian.net/browse/FIG-32029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-31761, FIG-32029: add `dir` reset to `ltr` for placeholders on `keyUp` submit as well

---

packages/ui/input/text/index.jsx
packages/ui/popup/content.css
packages/ui/styles/generic/typography.css
packages/ui/tooltip/index.jsx
packages/ui/tooltip/index.test.jsx

[FIG-32054](https://digital-science.atlassian.net/browse/FIG-32054)
[FIG-32053](https://digital-science.atlassian.net/browse/FIG-32053)
[FIG-32029](https://digital-science.atlassian.net/browse/FIG-32029)
[FIG-31761](https://digital-science.atlassian.net/browse/FIG-31761)
[FIG-32054]: https://digital-science.atlassian.net/browse/FIG-32054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FIG-32053]: https://digital-science.atlassian.net/browse/FIG-32053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FIG-32029]: https://digital-science.atlassian.net/browse/FIG-32029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FIG-31761]: …

Add reset to LTR on blur, fix padding for popup

---

packages/ui/textEditor/Lexical/components/LinkEditor/LinkEditor.jsx

[FIG-31814](https://digital-science.atlassian.net/browse/FIG-31814)
[FIG-31814]: https://digital-science.atlassian.net/browse/FIG-31814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-31814: fix unable to fully delete value in link editor input

---

packages/ui/tooltip/index.jsx

[FIG-32161](https://digital-science.atlassian.net/browse/FIG-32161)
https://github.com/figshare/fcl/assets/63391401/ed60614c-e6a9-4046-91b2-b0ee7fea0fe7
[FIG-32161]: https://digital-science.atlassian.net/browse/FIG-32161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-32161: Added displayDelay - tooltip

---

packages/ui/overlay/header/overlayHeader.jsx

[FIG-31806](https://digital-science.atlassian.net/browse/FIG-31806)
[FIG-31806]: https://digital-science.atlassian.net/browse/FIG-31806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-31806: fix overlay navigation tabindex issues

---

packages/ui/overlay/footer/overlayFooter.css
packages/ui/overlay/footer/overlayFooter.jsx
packages/ui/overlay/footer/overlayFooter.test.jsx
stories/overlay/overlay.stories.mdx

resolves: https://digital-science.atlassian.net/browse/FIG-32303
- added `OverlayFooter.Primary` layout slot component
- added `OverlayFooter.Secondary` layout slot component

FIG-32303: added Secondary and Primary OverlayFooter slot components

---

packages/ui/package-lock.json
packages/ui/package.json

- added Secondary and Primary layout components

:rocket: rel-1.3.14

---

packages/ui/textEditor/Lexical/components/LinkEditor/LinkEditor.css
packages/ui/textEditor/Lexical/components/LinkEditor/LinkEditor.jsx

[FIG-32323](https://digital-science.atlassian.net/browse/FIG-32323)
[FIG-32323]: https://digital-science.atlassian.net/browse/FIG-32323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-32323: update lexical link editor overlay

---

packages/ui/textEditor/Lexical/components/Toolbar/commands.jsx

[FIG-31368](https://digital-science.atlassian.net/browse/FIG-31368)
[FIG-31368]: https://digital-science.atlassian.net/browse/FIG-31368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-31368: Add target attribute to pasted links in lexical

---

packages/ui/button/genericButton/index.jsx

[FIG-32192)](https://digital-science.atlassian.net/browse/FIG-32192)

FIG-32192: fix genericButton tooltip position on initial focus

---

packages/ui/textEditor/Lexical/nodes/CustomTextNode.jsx

[FIG-31829](https://digital-science.atlassian.net/browse/FIG-31829)
[FIG-31829]: https://digital-science.atlassian.net/browse/FIG-31829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-31829: fix paste of entire paragraph instead of selection inside lexical

---

packages/ui/textEditor/Lexical/nodes/CustomTextNode.jsx

[FIG-31829](https://digital-science.atlassian.net/browse/FIG-31829)
[FIG-31829]: https://digital-science.atlassian.net/browse/FIG-31829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-31829: add node key for CustomTextNode clone

---

packages/ui/tooltip/index.jsx

[FIG-32462](https://digital-science.atlassian.net/browse/FIG-32462)
https://github.com/figshare/fcl/assets/63391401/6b7e83f0-8cfe-4b48-b508-56b11d20b62a
[FIG-32462]: https://digital-science.atlassian.net/browse/FIG-32462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-32462: The tooltip is displayed correctly

---

packages/ui/package-lock.json
packages/ui/package.json

:rocket: rel-1.3.16

---

packages/ui/package-lock.json
packages/ui/package.json

-  do not show button tooltips on first programatic focus into an overlay header.

:rocket: rel-1.3.18

---

packages/ui/overlay/header/overlayHeader.css

[FIG-33065](https://digital-science.atlassian.net/browse/FIG-33065)
[FIG-33065]: https://digital-science.atlassian.net/browse/FIG-33065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-33065: fix close button height on mobile

---

packages/ui/icons/indeterminate/index.jsx
packages/ui/input/checkbox/index.jsx
stories/input/checkbox/checkbox.stories.mdx

[FIG-31869](https://digital-science.atlassian.net/browse/FIG-31869)
[FIG-33151]: https://digital-science.atlassian.net/browse/FIG-33151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FIG-31869]: https://digital-science.atlassian.net/browse/FIG-31869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-31869: Add Indeterminate state for checkbox component

---

packages/ui/input/date/index.jsx

[FIG-33333](https://digital-science.atlassian.net/browse/FIG-33333)
https://github.com/figshare/fcl/assets/63391401/be9c9d11-b718-4f1a-856c-ce3e42ed5bdb
[FIG-33333]: https://digital-science.atlassian.net/browse/FIG-33333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-33333: Datepicker: Month / Year selector - fix

---

packages/ui/package-lock.json
packages/ui/package.json

- fixing date picker calendar bug when input is focused.

:rocket: rel-1.3.22

---

packages/ui/input/checkbox/components/checkmark.css
packages/ui/styles/settings/colors.css

[FIG-33151](https://digital-science.atlassian.net/browse/FIG-33151)
[FIG-33151]: https://digital-science.atlassian.net/browse/FIG-33151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-33151: update input type checkbox styling

---

packages/ui/input/checkbox/components/switch.css

[FIG-33289](https://digital-science.atlassian.net/browse/FIG-33289)
[FIG-33289]: https://digital-science.atlassian.net/browse/FIG-33289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-33289: update style for input checkbox

---

packages/ui/input/search/index.css

[FIG-33149](https://digital-science.atlassian.net/browse/FIG-33149)
https://github.com/figshare/fcl/assets/63391401/c9f08ddc-0e9a-4bc5-a085-b0c1b832e043
[FIG-33149]: https://digital-science.atlassian.net/browse/FIG-33149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-33149: Search:  input height - fix

---

Makefile

Adding makefile definition for install and build steps

adding makefile

---

packages/ui/overlay/header/overlayHeader.css
packages/ui/overlay/header/overlayHeader.jsx

[FIG-33161](https://digital-science.atlassian.net/browse/FIG-33161)
1. We cannot reach “Find out more about persistent identifiers.” link when using TABS or SHIFT +TABS
4. DOI overlay: “Find out more about DOIs and other persistent identifiers” link is the last focusable element instead of second
[FIG-33161]: https://digital-science.atlassian.net/browse/FIG-33161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-33161: Overlay header - focus - fix

---

packages/ui/input/checkbox/components/switch.css
packages/ui/input/checkbox/index.css

[FIG-33588](https://digital-science.atlassian.net/browse/FIG-33588)
[FIG-33588]: https://digital-science.atlassian.net/browse/FIG-33588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-33588: switch component -> fix focus and background colors

---

packages/ui/package-lock.json
packages/ui/package.json

:rocket: rel-1.3.24

---

packages/ui/input/checkbox/components/checkmark.css
packages/ui/input/checkbox/components/checkmark.jsx
packages/ui/input/checkbox/index.jsx
packages/ui/styles/settings/colors.css
stories/input/checkbox/checkbox.stories.mdx

[FIG-33762](https://digital-science.atlassian.net/browse/FIG-33762)
[FIG-33762]: https://digital-science.atlassian.net/browse/FIG-33762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-33762: Stats page: 'Views'/ 'Downloads'

---

packages/ui/package-lock.json
packages/ui/package.json

- added additional themes
- improved styling

:rocket: rel-1.3.25

---

packages/ui/package-lock.json
packages/ui/package.json

:rocket: rel-1.3.28

---

packages/ui/helpers/utils/getSelectableNeighbour.js

[FIG-33770](https://digital-science.atlassian.net/browse/FIG-33770)
[FIG-33770]: https://digital-science.atlassian.net/browse/FIG-33770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-33770: Manage identifiers accessibility

---

packages/ui/package-lock.json
packages/ui/package.json

- exclude disabled elements from focus cycle

:rocket: rel-1.3.29

---

packages/ui/toggletip/index.jsx

[FIG-34935](https://digital-science.atlassian.net/browse/FIG-34935)
[FIG-34935]: https://digital-science.atlassian.net/browse/FIG-34935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-34935: Create new item - Multiple item type tooltips- fix

---

packages/ui/package-lock.json
packages/ui/package.json

- fix uuid `crypto` usage issue in `ssr` build for toggletip ids

:rocket: rel-1.3.32

---

packages/ui/package-lock.json
packages/ui/package.json

- Added new `Fieldset` component to library.
> used to group inputs and provide a description for the group.
- Added a `label` to SearchInput that can link to the input and describe it.
- Added the option to set visually hidden text content for any Button by setting a `value` string property.

:rocket: rel-1.4.0

---

packages/ui/package-lock.json
packages/ui/package.json

- fixed @loadable/component isuse.
- fixed @loadable/component isuse.

:rocket: rel-1.4.1

---

packages/ui/textEditor/Lexical/index.jsx

[FIG-35297](https://digital-science.atlassian.net/browse/FIG-35297)
[FIG-35297]: https://digital-science.atlassian.net/browse/FIG-35297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-35297: add the id on lexical editor

---

packages/ui/input/search/index.jsx

Add url `data-attr` to searchInput button

---

packages/ui/alerts/alerts.css
packages/ui/alerts/alerts.jsx

- removing timeouts on unmount
- removed bottom margin from alerts wrapper
- added initialMessages property

FIG-35966: clear timeouts at unmount

---

packages/ui/package-lock.json
packages/ui/package.json

• removing timeouts on unmount
• removed bottom margin from alerts wrapper
• added initialMessages property

:rocket: rel-1.4.4

---

packages/ui/alerts/alerts.css
packages/ui/alerts/alerts.jsx
packages/ui/input/search/index.jsx

- fixing issue where `value` was not updated correctly
- added `margin` modifier

adding margin class to Alerts, fixing value ommission in SearchInput

---

packages/ui/package-lock.json
packages/ui/package.json

- fixing issue where `value` was not updated correctly
- added `margin` modifier

:rocket: rel-1.4.5

---

packages/ui/button/genericButton/index.jsx

[FIG-36391](https://digital-science.atlassian.net/browse/FIG-36391)
[FIG-36391]: https://digital-science.atlassian.net/browse/FIG-36391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-36391: iconBtn tooltip - fix

---

packages/ui/package-lock.json
packages/ui/package.json

- tooltip closed upon button visibility loss.
- added `guard` function for use in isomorphic rendering scenarios.

:rocket: rel-1.4.6

---

packages/ui/package-lock.json
packages/ui/package.json

- added new large chevron down icon

:rocket: rel-1.4.7

---

packages/ui/package-lock.json
packages/ui/package.json

:rocket: rel-1.4.8

---

packages/ui/package-lock.json
packages/ui/package.json

:rocket: rel-1.4.9

---

packages/ui/package-lock.json
packages/ui/package.json

- update prefix styling (width, wrap behaviour)
- allow more props to be overwritten

:rocket: rel-1.4.10

---

packages/ui/button/genericButton/index.jsx

[FIG-36455](https://digital-science.atlassian.net/browse/FIG-36455)
[FIG-36455]: https://digital-science.atlassian.net/browse/FIG-36455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-36455: Thumbnail view: Tooltip for Download button is displayed

---

packages/ui/package-lock.json
packages/ui/package.json

- added delay to tooltip observer initialization

:rocket: rel-1.4.11

---

packages/ui/input/search/index.jsx

Search Input, return focus to input on clear

---

packages/ui/package-lock.json
packages/ui/package.json

- move focus to input after clearing

:rocket: rel-1.4.12

---

packages/ui/package-lock.json
packages/ui/package.json

- modified background for white overlay styling.

:rocket: rel-1.5.1

---

packages/ui/avatar/index.jsx

- fix broken reference to `url` value.

fix url reference in Avatar component

---

packages/ui/package-lock.json
packages/ui/package.json

- fix a broken reference to the `url` value

:rocket: rel-1.5.2

---

packages/ui/package-lock.json
packages/ui/package.json

- added new icons for certain web API providers.

:rocket: rel-1.5.4:

---

packages/ui/avatar/index.jsx

[FIG-39661](https://digital-science.atlassian.net/browse/FIG-39661)
[FIG-39661]: https://digital-science.atlassian.net/browse/FIG-39661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-39661: hide avatar image when error on load

---

packages/ui/helpers/useControllableState.jsx
packages/ui/tabs/Tabs.css
packages/ui/tabs/Tabs.jsx
packages/ui/tabs/index.jsx
stories/tabs/index.stories.mdx

A component set to render TabLists and TabPanels
A hook to provide internal state and allow it to be controlled through a { value, defaultValue, onChange } props set.

[new] tabs component

---

packages/ui/package-lock.json
packages/ui/package.json

:rocket: rel-1.5.6

---

packages/ui/button/button/index.css
packages/ui/styles/generic/normalize.css

[FIG-40189](https://digital-science.atlassian.net/browse/FIG-40189)
[FIG-40189]: https://digital-science.atlassian.net/browse/FIG-40189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-38717 add underline to nonbutton links

---

packages/ui/package-lock.json
packages/ui/package.json

- updated link styles to contain underlines
- updated link styles to contain underlines

:rocket: rel-1.5.7

---

packages/ui/package-lock.json
packages/ui/package.json

- updated style to exclude `button` underline.

:rocket: rel-1.5.8

---

packages/ui/styles/settings/colors.css
packages/ui/tabs/Tabs.css

[FIG-40366](https://digital-science.atlassian.net/browse/FIG-40366)
[FIG-40366]: https://digital-science.atlassian.net/browse/FIG-40366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-40366: update border colour

---

packages/ui/package-lock.json
packages/ui/package.json

:rocket: rel-1.5.9

---

packages/ui/dropdown/Dropdown.jsx
packages/ui/dropdown/Dropdown.test.jsx
packages/ui/dropdown/Menu/Menu.jsx
packages/ui/dropdown/Menu/Menu.test.jsx
packages/ui/dropdown/Menu/index.jsx
packages/ui/dropdown/Toggle/Toggle.jsx
packages/ui/dropdown/Toggle/index.jsx
packages/ui/dropdown/context.js
packages/ui/dropdown/index.jsx
packages/ui/select/Content/Content.css
packages/ui/select/Content/Content.jsx
packages/ui/select/Content/Content.test.jsx
packages/ui/select/Content/index.jsx
packages/ui/select/Option/Option.css
packages/ui/select/Option/Option.jsx
packages/ui/select/Option/Option.test.jsx
packages/ui/select/Option/index.jsx
packages/ui/select/Option/utils.js
packages/ui/select/Select.css
packages/ui/select/Select.jsx
packages/ui/select/Select.test.jsx
packages/ui/select/Trigger/Trigger.css
packages/ui/select/Trigger/Trigger.jsx
packages/ui/select/Trigger/Trigger.test.jsx
packages/ui/select/Trigger/index.jsx
packages/ui/select/context.js
packages/ui/select/index.jsx

[FIG-40306](https://digital-science.atlassian.net/browse/FIG-40306)
[FIG-40306]: https://digital-science.atlassian.net/browse/FIG-40306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-40306: Move Select and Dropdown to FCL

---

packages/ui/package-lock.json
packages/ui/package.json

:rocket: rel-1.6.0

---

packages/ui/textEditor/Lexical/index.jsx

[FIG-40420](https://digital-science.atlassian.net/browse/FIG-40420)
[FIG-40420]: https://digital-science.atlassian.net/browse/FIG-40420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-40420: add required attribute to editor focus wrapper

---

packages/ui/input/checkbox/index.jsx

[FIG-40442](https://digital-science.atlassian.net/browse/FIG-40442)
[FIG-40442]: https://digital-science.atlassian.net/browse/FIG-40442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIG-40442: 17 - Incorrect tag for control - switch

---

packages/ui/package-lock.json
packages/ui/package.json

- added `react` and `svg` icon packages
- Updated accessibility related tags and attributes

:rocket: rel-1.6.3

---

packages/ui/alert/index.jsx
packages/ui/dropdown/Toggle/Toggle.jsx
packages/ui/select/Content/Content.css
packages/ui/select/Content/Content.jsx
packages/ui/select/Option/Option.css
packages/ui/select/Option/Option.jsx
packages/ui/select/Trigger/Trigger.css

+ https://digital-science.atlassian.net/jira/software/c/projects/FIG/issues/FIG-40442?jql=project%20%3D%20%22FIG%22%20AND%20assignee%20%3D%20currentUser%28%29%20ORDER%20BY%20created%20DESC - 129

Select: value object support

---

packages/ui/textEditor/Lexical/components/Toolbar/components/Tool.jsx

Fix Tool icon color

---

packages/ui/textEditor/Lexical/components/Toolbar/components/Tool.css
packages/ui/textEditor/Lexical/components/Toolbar/utils.jsx

Updated TextEditor icons with new set from icons/react

FIG-40987 updated toolbar icons

---

packages/ui/package-lock.json
packages/ui/package.json

- removed height attribute with auto
- replaced Alerts icons
- replaced TextEditor icons

:rocket: rel-1.6.6

---

package-lock.json
package.json
packages/ui/alerts/alerts.css
packages/ui/helpers/useEventListener.jsx
packages/ui/helpers/useIsomorphicLayoutEffect.jsx
packages/ui/helpers/utils/debounce.js
packages/ui/tabs/Tabs.css
packages/ui/tabs/Tabs.jsx
stories/tabs/index.stories.mdx

- Adding resizing feature for Tabs component

FIG-41501: tabs resizing

---

packages/ui/input/text/utils.js
packages/ui/textEditor/Lexical/index.jsx

- adding `dir` property to `H` tags as well.

FIG-41535: update to dir on HeadingNode

---

packages/ui/package-lock.json
packages/ui/package.json

- updated behaviour when resizing. Added dropdown for overflowing tabs.
- reset positioning of warning icon

:rocket: rel-1.6.7

---

package-lock.json
package.json
packages/ui/package-lock.json
packages/ui/package.json

fixing package-lock issue for packages/ui

fixing package issue

---

packages/ui/package-lock.json
packages/ui/package.json

- updates to click behaviour and props passing
- revert dir update for headings

:rocket: rel-1.6.9
